### ISSUE TITLE
Add version to the Salesforce Hook

### ISSUE THREAD

**Issue by ldacey** [Jalepeno112/airflow-salesforce#1]
I am having trouble connecting to certain tables because it requires a certain version.

Would it be safe for me to edit the source code I have and add another parameter which looks at the 'Extras' field and grabs the version?

security_token=self.extras['security_token'],
version=self.extras['version']

This connection works, but if I remove the version portion it gives me a Malformed Request error.
Salesforce(username='name', password='pass', security_token='key', version='39.0')

**Comment by TheF1rstPancake** [comment]
Well that's odd.  I wasn't aware that certain objects were only accessible through certain versions.

That would be do the trick.  The "extras" in the connection settings is a JSON formatted string that is then converted to a dictionary.  If you could submit a pull request with the change that would be awesome!  If not, I can do it.  You would want the "version" field to be optional though.  So it would be `version=self.extras.get('version', None)`
